using System.ComponentModel.DataAnnotations;

namespace EnterpriseAssetManager.Models;

public class AssetRequest
{
    public int Id { get; set; }

    // Human friendly unique number such as REQ-2026-000123. Generated by the service.
    [Required]
    [MaxLength(30)]
    public string RequestNumber { get; set; }

    public int RequestedByUserId { get; set; }
    public User RequestedByUser { get; set; }

    public int AssetCategoryId { get; set; }
    public AssetCategory AssetCategory { get; set; }

    // The concrete asset is only attached when the request is fulfilled.
    public int? AssetId { get; set; }
    public Asset Asset { get; set; }

    [Required]
    [MaxLength(500)]
    public string BusinessReason { get; set; }

    public RequestPriority Priority { get; set; } = RequestPriority.Medium;

    public RequestStatus Status { get; set; } = RequestStatus.Pending;

    [MaxLength(500)]
    public string ManagerComments { get; set; }

    public DateTime RequestedAt { get; set; } = DateTime.UtcNow;

    public DateTime? ReviewedAt { get; set; }

    public int? ReviewedByUserId { get; set; }
    public User ReviewedByUser { get; set; }
}
